Feature/tachikawa
hr-js/sam_api_server pull request #15
Opened 2018-05-12 08:09 UTC by Tchikawa

・mgmtSchema.jsを作成しました
・エラーをerrorhelper.jsにまとめました。
よろしくお願いします。

2018-05-12 08:10 UTC, Tchikawa commented on assetes/mgmtSchema.js
> +          pattern: '^[0-9]{8}$',
\dは使えなかったので、[0-9]にしてます。
{4}{2}{2}だと、4文字以上が全部許容されてしまうので、^[0-9]{8}$にしてます。

2018-05-12 08:10 UTC, Tchikawa commented on assetes/mgmtSchema.js
> +          pattern: '^[0-9]{8}$',
上と一緒です。

2018-05-12 08:17 UTC, ghost commented
プルリクエストの名前をちゃんと書いてください。

2018-05-12 08:18 UTC, ghost commented
何を作成したかはコミットをみたらわかるので、何故したかを説明文に書いてください。

2018-05-18 23:58 UTC, krhrtky requested changes
ソース自体は問題ないかと。
@kakaka19 が指摘している部分は直したほうがいいですね。
自分が気になったところとか見てほしいところとかは、ソースにコメントするよりPRのメッセージに載せるほうがいいでしょう。
下記を参考にしてみてもいいと思います。
https://ics.media/entry/14449

2018-05-18 23:58 UTC, krhrtky commented on routes/management.js
> +  } = require('../assets/mgmt_schema');
schemeのファイル名が合わなくなってしまっているので、統一しましょう。
個人的にはキャメルケースでいいと思います。

2018-05-18 23:58 UTC, krhrtky commented on assetes/mgmtSchema.js
> +} = require('./util/errorHelper.js');
@kakaka19 
~Helperっていうファイルとかクラスって共通関数が入っているイメージがあるんですけど、どういうときに使ってますか？
commonSchemaとかでもいいのかなと。

2018-05-23 14:19 UTC, ghost requested changes
@Tchikawa 
確認お願いします

2018-05-23 14:19 UTC, kakaka19 commented on assetes/mgmtSchema.js
> +      responce: {
responce => responseでは？

2018-05-23 14:19 UTC, kakaka19 commented on assetes/mgmtSchema.js
> +      responce: {
他の箇所も間違ってたので確認よろしくお願いします

2018-05-23 14:19 UTC, kakaka19 commented on assetes/util/errorHelper.js
> +const ANY_ERROR_RESPONSE = {
`ANY`が包括的すぎる名前なので、どのようなエラーを返すかを示す名前にしてみてください(できればでいいです)。

2018-05-23 14:19 UTC, kakaka19 commented on routes/management.js
> +        .getAggregate(request.sort)
`provider`の呼び出しは書かなくていいです。代わりにTODOを書いといてくれると嬉しいです。

2018-05-23 14:19 UTC, kakaka19 commented on assetes/util/errorHelper.js
> +      type: 'string',
`type: 'object'` では？

2018-05-26 07:18 UTC, Tchikawa commented on assetes/mgmtSchema.js
> +      responce: {
responseでした。修正しました

2018-05-26 07:18 UTC, Tchikawa commented on assetes/util/errorHelper.js
> +      type: 'string',
` type : 'object' ` でした。修正しました。

2018-05-26 07:18 UTC, Tchikawa commented on routes/management.js
> +        .getAggregate(request.sort)
provider関連の部分を消してTODOにしました。

2018-05-26 07:24 UTC, krhrtky commented
@Tchikawa 
指摘箇所は修正できれいると思うので大丈夫だと思います。

2018-05-26 07:24 UTC, krhrtky approved these changes

2018-05-26 08:50 UTC, merged