ディレクトリ構成を通変更
hr-js/sam_api_server pull request #16
Opened 2018-05-28 13:17 UTC by krhrtky

# 概要

- アプリのディレクトリ構成を変更。

## 目的

- 曖昧になっていた構成を見直すことで、見通しのよいディレクトリにする。

- 見通しをよくすることで、追加・変更しやすいようにする。

## 備考

- schemaのファイル名をroutingのファイル名と合わせました
。

- サーバの起動と既存のテストがと通るのを確認済みです。

2018-05-28 13:17 UTC, krhrtky commented
conflict しているので解消してからまた通知します。

2018-05-28 14:11 UTC, krhrtky commented
@kakaka19 @Tchikawa 
解消しました。
確認よろしくおねがいします。

2018-06-02 07:36 UTC, kakaka19 commented
https://github.com/hr-js/sta_access_manager/issues/115　での内容が反映されてないです

2018-06-02 07:38 UTC, ghost requested changes
https://github.com/hr-js/sta_access_manager/issues/115
でのやりとりが反映されていないので差し戻します

2018-06-09 06:43 UTC, kakaka19 commented
@krhrtky 
fastifyのscheme定義って**schem.jsって名前にしないといけないんでしたっけ？

2018-06-09 06:47 UTC, krhrtky commented
@kakaka19 
統一する必要はないです。
だけど、明示的に名前をつけておいたほうが親切だと思うので。
controllerとかも追々変更したいです。

2018-06-09 06:49 UTC, kakaka19 commented
@krhrtky 
shemeってディレクトリの下にあるなら*shema.jsってファイル名にする必要ないかなと思ったんですが、どうでしょう？

2018-06-09 07:13 UTC, Tchikawa commented
@kakaka19 
たしかに

2018-06-09 07:33 UTC, krhrtky commented
@kakaka19 
@Tchikawa 
一長一短あって、決めの問題なのは間違いないんだけど、
〜Schema.js とした場合、
`require('./schema/〜Schema')だと冗長な感じが出る。
`require('./〜Schema')` となったときにはファイル名だけで内容が想像できる。
あとファイル数が増えたときに検索しやすい。

ファイル数は増えないし、
冗長なのが嫌なら変えます。

2018-06-09 08:40 UTC, kakaka19 commented
@krhrtky 
>require('./schema/〜Schema')だと冗長な感じが出る。require('./〜Schema')` となったときにはファイル名だけで内容が想像できる。

schemaってディレクトリにいる時点でschmaであることを示唆しているからいいんじゃない？ファイル名で内容が想像できるのは**Schemaじゃなくての`**`の部分だと思う(errorとか、usersとか、managementとかの部分ね)。

> あとファイル数が増えたときに検索しやすい。

schemaディレクトリ下で検索かけると思うから特にメリットではないかな。

2018-06-09 08:45 UTC, krhrtky commented
@kakaka19 
了解、同じファイル名があってもディレクトリで意味もわかるとは思うので、ファイル名変えます。

2018-06-09 09:08 UTC, ghost approved these changes

2018-06-10 05:50 UTC, kakaka19 commented
@Tchikawa 
これマージしちゃって大丈夫ならやっちゃってください

2018-06-10 06:46 UTC, merged