ソースからswagger uiを作成するプラグインの導入
hr-js/sam_api_server pull request #32
Opened 2018-08-11 01:56 UTC by krhrtky

## 概要
- swaggerでのAPIの管理の簡略化
    - swagger editor で最初にAPIを要件定義するのはいい
    - ただ、途中で変更が発生したときにソースとswagger file を編集すると管理しにくい
    - [fastify-swagger](https://github.com/fastify/fastify-swagger)を使うとソースのrooting, schemeからAPIドキュメントを作成してくれる。
 - 確認方法
    - アプリを起動: `yarn run dev:http`
    - ブラウザで `http://<domain>/documentation/` を開く

- 既存のswagger.ymlは確認が終われば不要(どっちが正しいかわからなくなるのが嫌なので)

2018-08-12 13:34 UTC, krhrtky commented
@kakaka19 
@ikkyu-3  とAPIを再確認しました。
↑の方法でfastify のドキュメント・swagger-ui で`swagger.yml` の確認をお願いします。

2018-08-12 18:51 UTC, ikkyu-3 requested changes
変更してほしい箇所があるので確認お願いします。

また、Files Changedにない  
**fastify のドキュメントにあるdefaultタグ**で定義しているAPIの確認をしてほしいです。

確認したところ

- 400の記述が足りない
- Parametersの記述がされていない

などあるので、その辺り確認してもらっていいですか？よろしくお願いします。

2018-08-12 18:51 UTC, ikkyu-3 commented on swagger/swagger.yaml
>              properties:
`POST /register`の400(Bad Request)で参照するschemaは、`#/definitions/ServerError`を使用する認識です。

ケースとしては
1. パラメータが異常
1. 既に登録されているidを指定

ですね。

```
{
  "error": {
    "message": "string" // 1と2でメッセージ分けれるといいです
  }
}
```

2018-08-12 18:51 UTC, ikkyu-3 commented on swagger/swagger.yaml
>            schema:
`POST /register`の400(Bad Request)と同じく、参照するschemaは、#/definitions/ServerErrorを使用する認識です。

2018-08-12 18:51 UTC, ikkyu-3 commented on swagger/swagger.yaml
>        summary: 入室処理
`退出処理`に変更お願いします。

2018-08-12 18:51 UTC, ikkyu-3 commented on swagger/swagger.yaml
> +        description: 入室処理
`退出処理`に変更お願いします。

2018-08-12 18:51 UTC, ikkyu-3 commented on swagger/swagger.yaml
>            description: 入室処理成功
`退出処理成功`に変更お願いします。

2018-08-12 18:51 UTC, ikkyu-3 commented on app/controller/schema/users.js
> +        '400': VALIDATION_ERROR_RESPONSE,
`400`のみ使用するので、`4xx`は必要ないかと思います。

また値は  
`VALIDATION_ERROR_RESPONSE` => `CLIENT_ERROR_RESPONSE `に変更ですね。

2018-08-12 18:51 UTC, ikkyu-3 commented on app/controller/schema/users.js
> +          '500': INTERNAL_SERVER_ERROR_RESPONSE,
400系, 500系が表示されてません。
一度確認お願いします。

2018-08-12 18:51 UTC, ikkyu-3 commented on app/controller/schema/users.js
>        },
現状は`400`のみ使用するので、4xxは必要ないかと思います。  
また値は
VALIDATION_ERROR_RESPONSE => CLIENT_ERROR_RESPONSEに変更でお願いします。

(404必要ですね...使用予定は先のことなので、**現時点で404は増やさなくていい**と思います。使用する時になったら、他の変更も入りそうなので)

2018-08-12 18:51 UTC, ikkyu-3 commented on app/controller/schema/users.js
>    UPDATE_SCHEMA: {
表示では`POST`になってますね。swaggerでは`PUT`なので、すぐ変更できるなら`PUT`に変更したいですね。  
ですが、このAPIを使用するのはまだ先なので、優先度は低いです。

2018-08-19 07:00 UTC, ikkyu-3 commented on app/controller/schema/users.js
> +      querystring: {
idがqueryになっているので、pathに変更お願いします。公式みてみると

```
    params: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: '説明'
        }
      }
    },
```

こんな感じに変更になるかと思います。

2018-08-19 07:00 UTC, ikkyu-3 commented on app/controller/schema/users.js
> +            properties: {
データ構造の確認です。

```
{
  "id": "string",
  "user": {
    "isEntry": true
  }
}
```

swagger.yamlだとこの構造ですが、どっちにするのでしたっけ？
コードの改修が他にも必要ならそのままで大丈夫です。

2018-08-25 06:26 UTC, krhrtky reviewed
指摘箇所を修正しました

2018-08-25 06:26 UTC, krhrtky commented on app/controller/schema/users.js
> +      querystring: {
`params` なるほど。
修正しました。

2018-08-25 06:26 UTC, krhrtky commented on app/controller/schema/users.js
> +            properties: {
そっちが正しいですね。
あと配列で返すとかってなってしまっていたので、`object`で返すように直しました。

2018-08-26 09:46 UTC, ikkyu-3 approved these changes

2018-08-26 09:47 UTC, ikkyu-3 commented
@krhrtky 
確認しました。大丈夫です。

2018-08-30 13:06 UTC, kakaka19 commented
@krhrtky conflictの解消お願いします

2018-09-01 02:30 UTC, krhrtky commented
@kakaka19 
解消しました

2018-09-01 02:31 UTC, merged